<a href="https://colab.research.google.com/github/Truth30Lilian/Truth_codes/blob/main/Day_3_Data_Cleaning_Lilian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded= files.upload()

Saving pharmacy_messy (1).csv to pharmacy_messy (1).csv

In [4]:
import pandas as pd
df= pd.read_csv("pharmacy_messy (1).csv")
print("shape",df.shape)
df.head()

shape (200, 12)

,Receipt ID,BRANCH,Customer Type,Gender,Drug Category,Unit Price,Quantity,Total Amount,Date,Payment Method,Pharmacist Name,Rating
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,GHS 39.87,4,159.48,4/17/2023,Mobile Money,Ama Mensah,4.8
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,GHS 145.83,10,1458.30,"June 7, 2023",Mobile Money,NaN,8.8
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,GHS 189.64,9,1706.76,"January 9, 2023",Cash,Yaw Darko,5.2
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,GHS 106.14,4,424.56,2/23/2023,Card,Ama Mensah,5.5
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,GHS 133.76,1,133.76,6/27/2023,Cash,NaN,4.2

In [5]:
df.columns
for col in df.columns:
  print(repr(col))

'Receipt ID'
'BRANCH'
'Customer Type'
'Gender'
'Drug Category'
'Unit Price'
'Quantity'
'Total Amount'
'Date'
'Payment Method'
'Pharmacist Name'
'Rating'

In [9]:
df.columns= df.columns.str.lower().str.strip().str.replace(" ", " ")
print(df.columns.tolist())

['receipt id', 'branch', 'customer type', 'gender', 'drug category', 'unit price', 'quantity', 'total amount', 'date', 'payment method', 'pharmacist name', 'rating']

In [11]:
df=df.rename(columns={"receipt id":"receipt_id", "customer type":"customer_type", "drug category":"drug_category", "total amount":"total_amount", "payment method":"payment_method", "unit price":"unit_price", "pharmacist name":"pharmacist_name"})
print("Final column names")
print(df.columns.tolist())

Final column names
['receipt_id', 'branch', 'customer_type', 'gender', 'drug_category', 'unit_price', 'quantity', 'total_amount', 'date', 'payment_method', 'pharmacist', 'rating']


- Which columns had messy names?

No Column had a messy name

- What did you rename them to?

I just placed an underscore between the column names with two different words.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   receipt_id      200 non-null    object
 1   branch          200 non-null    object
 2   customer_type   200 non-null    object
 3   gender          200 non-null    object
 4   drug_category   200 non-null    object
 5   unit_price      200 non-null    object
 6   quantity        200 non-null    int64
 7   total_amount    188 non-null    float64
 8   date            200 non-null    object
 9   payment_method  200 non-null    object
 10  pharmacist      190 non-null    object
 11  rating          185 non-null    float64
dtypes: float64(2), int64(1), object(9)
memory usage: 18.9+ KB

In [13]:
df.isnull().sum()

receipt_id         0
branch             0
customer_type      0
gender             0
drug_category      0
unit_price         0
quantity           0
total_amount      12
date               0
payment_method     0
pharmacist        10
rating            15
dtype: int64


- Which columns have the wrong data type?
Columns 5,8,

- Which columns have missing values?

Columns 7,10,11.

In [14]:
print("Type Before:",df["unit_price"].dtype)
print(df["unit_price"].head())

Type Before: object
0     GHS 39.87
1    GHS 145.83
2    GHS 189.64
3    GHS 106.14
4    GHS 133.76
Name: unit_price, dtype: object

In [31]:
df["unit_price"] = df["unit_price"].astype(str)
df["unit_price"]= df["unit_price"].str.replace("GHS", " ").str.strip()
df["unit_price"]= pd.to_numeric(df["unit_price"], errors="coerce")
print("Type after:", df["unit_price"].dtype)
print(df["unit_price"].head())

Type after: float64
0     39.87
1    145.83
2    189.64
3    106.14
4    133.76
Name: unit_price, dtype: float64

In [32]:
print("Type before", df['date'].dtype)
print(df['date'].head())

Type before object
0          4/17/2023
1       June 7, 2023
2    January 9, 2023
3          2/23/2023
4          6/27/2023
Name: date, dtype: object

In [73]:

df["month"]=df["date"].dt.month
df['day']=df['date'].dt.day
df[["date", "month", "day"]].head()

        date  month  day
0 2023-04-17      4   17
3 2023-02-23      2   23
4 2023-06-27      6   27
6 2023-02-24      2   24
7 2023-02-18      2   18

In [75]:
df.dtypes

receipt_id                object
branch                    object
customer_type             object
gender                    object
drug_category             object
unit_price               float64
quantity                   int64
total_amount             float64
date              datetime64[ns]
payment_method            object
pharmacist                object
rating                   float64
month                      int32
day                        int32
dtype: object


- What was the type before and after for Unit Price?

Before: Object, After: Float64

- What was the type before and after for Date?


Before: Object,   After: Datetime64

In [76]:
print(df.isnull().sum())

receipt_id        0
branch            0
customer_type     0
gender            0
drug_category     0
unit_price        0
quantity          0
total_amount      0
date              0
payment_method    0
pharmacist        0
rating            0
month             0
day               0
dtype: int64

In [46]:
df["total_amount"]= df["total_amount"].fillna(df["total_amount"].mean())

df["rating"]= df["rating"].fillna(df["rating"].mean())

print("missing in total_amount:", df["total_amount"].isnull().sum())
print("missing in rating:", df["rating"].isnull().sum())

missing in total_amount: 0
missing in rating: 0

In [69]:
df["pharmacist"]= df["pharmacist"].fillna("Unknown")


print("missing in pharmacist:", df["pharmacist"].isnull().sum())

missing in pharmacist: 0

In [77]:
print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
receipt_id        0
branch            0
customer_type     0
gender            0
drug_category     0
unit_price        0
quantity          0
total_amount      0
date              0
payment_method    0
pharmacist        0
rating            0
month             0
day               0
dtype: int64

In [78]:
print("Rows before dropping", len(df) )

df=df.dropna()

print("Rows after dropping", len(df))

Rows before dropping 160
Rows after dropping 160

In [79]:
print(df.isnull().sum())

print("\nFinal shape:", df.shape)

receipt_id        0
branch            0
customer_type     0
gender            0
drug_category     0
unit_price        0
quantity          0
total_amount      0
date              0
payment_method    0
pharmacist        0
rating            0
month             0
day               0
dtype: int64

Final shape: (160, 14)


- How many missing values did you find in each column?


0 for all except for columns 7,10 and 11. Which I filled 12,10 and 15 respectively

- Which columns did you fill? What value did you use?

Columns 7,10 and 11. I used the mean value for numeric columns and "Unknown for text columns"

- How many rows did you lose after dropping?


40 rows